name: Checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
